"""Init

Revision ID: df005ebc3c31
Revises: bb3b58f471bd
Create Date: 2024-04-30 15:51:24.076371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df005ebc3c31'
down_revision: Union[str, None] = 'bb3b58f471bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformed_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'photo_url', name='unique_user_photo')
    )
    op.create_index(op.f('ix_transformed_photos_id'), 'transformed_photos', ['id'], unique=False)
    op.create_index(op.f('ix_transformed_photos_photo_url'), 'transformed_photos', ['photo_url'], unique=False)
    op.create_index(op.f('ix_transformed_photos_user_id'), 'transformed_photos', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'photos', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'photos', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    op.drop_index(op.f('ix_transformed_photos_user_id'), table_name='transformed_photos')
    op.drop_index(op.f('ix_transformed_photos_photo_url'), table_name='transformed_photos')
    op.drop_index(op.f('ix_transformed_photos_id'), table_name='transformed_photos')
    op.drop_table('transformed_photos')
    # ### end Alembic commands ###
